### ISSUE TITLE
Can't bind to 'xScale' since it isn't a known property of ':svg:g'

### ISSUE THREAD

**Issue by ahyos** [swimlane/ngx-charts#1088]
This is the same issue as https://github.com/swimlane/ngx-charts/issues/476

but the autor or anyone provided the solution.

Basically I tried to reproduce the demo in my app, because its hard to understand.

**Comment by liuhaoXD** [comment]
Just import `NgxChartsModule` by doing this

```typescript
@NgModule({
  imports: 
    ...
    NgxChartsModule,
    ...
  ],
   ...
})
```

A typical customized chart is like this:

```html
  <svg:g [attr.transform]="transform" class="line-chart chart">
    <svg:g ngx-charts-x-axis
           *ngIf="xAxis"
           [xScale]="xScale"
           [dims]="dims">
    </svg:g>
  </svg>
```

Angular will failed to parse `ngx-charts-x-axis` if you didn't import `NgxChartsModule`.

Attribute `g[ngx-charts-x-axis]` is defined [here](https://github.com/swimlane/ngx-charts/blob/master/src/common/axes/x-axis.component.ts#L15) and exported by [AxesModule](https://github.com/swimlane/ngx-charts/blob/master/src/common/axes/axes.module.ts)
 and the `AxesModule` will be exported by [ChartCommonModule](https://github.com/swimlane/ngx-charts/blob/master/src/common/chart-common.module.ts#L59)
and the  `ChartCommonModule` will be exported by [NgxChartsModule](https://github.com/swimlane/ngx-charts/blob/master/src/ngx-charts.module.ts#L19)

**Comment by vascofernandes** [comment]
I also get this problem with Ivy at version 9.0.0-next.3.

https://github.com/angular/angular/issues/30512

**Comment by tmk1991** [comment]
It's definitely an IVY problem. 8.2.2 and 8.2.6 has the same issue. Turn off IVY and it works.

**Comment by bobbyg603** [comment]
Thanks @tmk1991 I was able to get around this for now by setting enableIvy to false under angularCompilerOptions in the tsconfig.app.json file.

**Comment by vascofernandes** [comment]
The issue is still present in Angular 9.0.0-next.9 with Ivy enabled

**Comment by marjan-georgiev** [comment]
This should be fixed in 13.0.0.

**Comment by mikegoodstadt** [comment]
Was this fixed in 13.0.0 ?

**Comment by ChandlerBaskins** [comment]
Running into these issues as well. Angular version 10.1. But in my case its more than just xScale. Any workaround?

**Comment by SonicReal** [comment]
> Running into these issues as well. Angular version 10.1. But in my case its more than just xScale. Any workaround?
Try to use inline template instead of templateUrl. Helped me

**Comment by BasmaAltayeh** [comment]
still having this issue with angular 13.3.8 :(, I need to fix it but I tried everything, I tried the IVY false solution it didn't work, anyone has a solution?

**Comment by violet-brown** [comment]
After hitting the same issue, I was eventually able to get the combo chart seemingly fully working. Things that seemed to resolve my problems:
- Copy the code from the version of ngx-charts I was actually using, not the latest.
- Also copy `src/app/custom-charts/combo-chart/index.ts`. For some reason I ignored it at first.
- import _both_ `ComboChartComponent` _and_ `ComboSeriesVerticalComponent` in `app.module.ts` and put them both in the `declarations`.
- Change the import `projects/swimlane/ngx-charts/src/public-api` to `@swimlane/ngx-charts` in `combo-chart.component.ts`
- Change the imports `@swimlane/ngx-charts/common/*` all to just `@swimlane/ngx-charts` in `combo-series-vertical.component.ts`
- Add `// @ts-nocheck` to the start of both `combo-chart.component.ts` and `combo-series-vertical.component.ts` to suppress typing-related warnings, because there were so many I didn't want to go through and fix them all.
- Specify _all_ of the parameters for `combo-chart-component` that are specified in `src/app/app.component.html`, because many do not have defaults defined in `combo-chart.component.ts`.

Hopefully someone finds some of this helpful. For reference, I am using Angular 13.1.3 and ngx-charts 20.1.2.
