### ISSUE TITLE
no tooltips display in iOS

### ISSUE THREAD

**Issue by StephanieHohenberg** [swimlane/ngx-charts#1228]
Hi, 
we are using the charts cross plattform. But the tooltips of the charts are not triggered on the iPad, iOS version 12.1
Even in the [demo page](https://swimlane.github.io/ngx-charts/#/ngx-charts/bar-vertical) the tooltips are not displayed in this iOS version.

**Expected behavior**
displaying of tooltips on all plattforms

**Demo**
https://swimlane.github.io/ngx-charts/#/ngx-charts/bar-vertical

**Comment by chriszrc** [comment]
I can confirm, it works on chrome on android, but not chrome or safari on IOS :(

**Comment by kanikkwatra** [comment]
Are there any updates on this? I'm facing the same issue.

**Comment by vivek24** [comment]
In my case, the tooltips are showing only if you triple tap. But it works perfectly fine in android devices.

**Comment by joberthrogers18** [comment]
I have the same problem and only works if I do the same explained by @vivek24

**Comment by HusFNS** [comment]
Same problem here. We are using it actually in ionic for ios and android works fine but ios not.
any fix for this?

**Comment by HusFNS** [comment]
Problem is fixed in master but no release made. Can this be released?

**Comment by R1cs1KING** [comment]
setting overflow attribute of the svg to hidden seemed to solve the issue on Safari
`
svg.ngx-charts {
    overflow: hidden !important;
}
`

**Comment by axelgalicia** [comment]
Any update on this for iOS? Is this fix released? Having issues even after adding @R1cs1KING css.
Thanks

**Comment by R1cs1KING** [comment]
> Any update on this for iOS? Is this fix released? Having issues even after adding @R1cs1KING css.
> Thanks

I cannot recall testing it on iOS

**Comment by EmreAkkoc** [comment]
tooltip on heatmap didn't work in angular 11 with ngx-charts version 18 so I reverted back to version 16

**Comment by kappi94** [comment]
Any updates on this? How can this still not be resolved? Experience the same problem on iOS devices

**Comment by JMTrainee** [comment]
Any status update on release ?

**Comment by gurpreetKobe** [comment]
Kindly update
