### ISSUE TITLE
How to set the width of Vertical Bar Charts?

### ISSUE THREAD

**Issue by ChitrajanDhiman** [swimlane/ngx-charts#692]
I am using Vertical Stacked Bar Chart in my project. I don't know how to adjust the width of the bar of chart.
If I have multiple bars on charts, it looks good but if I have a single bar on charts it takes the whole space on chart and looks like a piece of block on chart. If there is a possible way to fix this issue please help me.

**Comment by menzie2** [comment]
[barPadding]="number" <- add this property to the page component you are using

Increasing this number will make the bar chart width smaller.  I would dynamically (in your component) adjust this number based on the number of data objects you have.

Try on:
https://swimlane.gitbooks.io/ngx-charts/content/charts/bar-vertical-stacked.html

**Comment by galvakojis** [comment]
it does not fix the issue if you have one bar in chart
So can i achieve the result represented in picture?
![selection_492](https://user-images.githubusercontent.com/17315578/39707028-d9d49154-521b-11e8-9e78-02c3ae86c41a.png)

**Comment by galvakojis** [comment]
Maybe you can give me an example, cause it don't let me to display 4 bars with null data

 ```
           for(let i=0; i < 5-datas.length; i++){
                array.push({
                    name: "i"+i,
                    value: i
                })
            }
```

**Comment by galvakojis** [comment]
more or less :sad
my work around:
```

 if(datas.length < 5){
            let empty = '  ';
            for(let i=0; i<5-datas.length; i++){
                array.push({
                    name: empty.repeat(i+1),
                    value: 0
                })
            }
        }
```

**Comment by thesayyn** [comment]
is there any news on it ?

**Comment by frankdavidcorona** [comment]
@thesayyn You can set `barPadding` and at increase the space between graphs you decrerase the width of bars.

**Comment by galvakojis** [comment]
@frankdavidcorona it is not working if you have only one bar!

**Comment by frankdavidcorona** [comment]
@galvakojis That's rigth, my appologies.

**Comment by soothran** [comment]
Even if I'm passing null data i can see lines with 1 px height for each bar with null data 
Is there any other way to set a fixed with for each bar?
In my case I'm showing a fixed number of bars all time.

**Comment by ChitrajanDhiman** [comment]
@soothran Please try to pass 0 instead of null

**Comment by soothran** [comment]
Yeah I tried. But no luck.
0 is my yscalemin value. I think that's why it is showing a line in xaxis

**Comment by JohnProg** [comment]
is there any news on it ?

**Comment by kultigin** [comment]
why is this closed when it is not solved? clearly the first comment is on having one bar not multiple...

**Comment by issamalshamaly** [comment]
please, I really need this issue to be solved!!

**Comment by cdhiman** [comment]
Hi @issamalshamaly 
I already resolved this issue earlier but not able to provide it here with example. Now I have an working example for this issue, you can clone it from "https://github.com/ChitrajanDhiman/VerticalChart".
The default behavior of chart is Image-1.png
![Image-1](https://user-images.githubusercontent.com/44690784/60791274-e9171280-a180-11e9-9f07-39047742063b.png)
After resolving it will look like Image-2.png
![Image-2](https://user-images.githubusercontent.com/44690784/60791324-064be100-a181-11e9-80bc-440acf7d1a23.png)
I hope it will resolve your issue

**Comment by martheli** [comment]
I tried adding some bars with 0 as value and it still shows a blank section of the graph, doesn't push all the bars to the right like the second photo.

**Comment by cdhiman** [comment]
![with-x-axis](https://user-images.githubusercontent.com/44690784/80669373-e4ca3600-8ac1-11ea-84cb-8de59b7cac11.png)

@martheli Its working with X axis also.
Can you show me your code to understand the issue?

**Comment by martheli** [comment]
@cdhiman your example still has numbers on the bottom axis. It has "2", "3", "4" etc....how to remove those?

**Comment by ChitrajanDhiman** [comment]
Hi @martheli, name for x-axis must b unique, so in this example I have just passed index number in name for empty data. I know this is not a proper solution for the problem, its just a work around for the time. We can avoid these numbers by adding empty spaces as name to avoid displaying index in x-axis. I have made changes in file - https://github.com/ChitrajanDhiman/VerticalChart/blob/master/src/app/app.component.ts

Now its look like -

![2020-07-02_1157](https://user-images.githubusercontent.com/28748282/86323990-7b021000-bc5b-11ea-916e-06bd33faf34e.png)

**Comment by Sina7312** [comment]
I really need this too, it would be great if there were a way to solve this!

**Comment by Pragyansh99** [comment]
Is this solved! I am facing the same issue on my project! I have tried using for loop to add null bars but then I get empty as a legend on the chat! Is there any workaround for this yet?

**Comment by stochmalm** [comment]
Here's my hack, add empty data to your chart:
```
// Hack: fill chart with dummy data for better bar scaling purposes.
   for (let i = this.chartData.length ; i < 10; i++){
     this.chartData.push({name: 'REPLACE_ME_' + i+'', value: 0});
  }
```
And then add tick format to your ngx-charts-bar-vertical component:
```
            <ngx-charts-bar-vertical
                [results]="chartData"
                [noBarWhenZero]="true"
                [xAxisTickFormatting]="tickFormat">
        </ngx-charts-bar-vertical>

    tickFormat(name: string) {
        return name.startsWith('REPLACE_ME') ? '' : name;
    }
```

**Comment by sujitha454** [comment]
> Hi @issamalshamaly I already resolved this issue earlier but not able to provide it here with example. Now I have an working example for this issue, you can clone it from "https://github.com/ChitrajanDhiman/VerticalChart". The default behavior of chart is Image-1.png ![Image-1](https://user-images.githubusercontent.com/44690784/60791274-e9171280-a180-11e9-9f07-39047742063b.png) After resolving it will look like Image-2.png ![Image-2](https://user-images.githubusercontent.com/44690784/60791324-064be100-a181-11e9-80bc-440acf7d1a23.png) I hope it will resolve your issue


> Hi @issamalshamaly I already resolved this issue earlier but not able to provide it here with example. Now I have an working example for this issue, you can clone it from "https://github.com/ChitrajanDhiman/VerticalChart". The default behavior of chart is Image-1.png ![Image-1](https://user-images.githubusercontent.com/44690784/60791274-e9171280-a180-11e9-9f07-39047742063b.png) After resolving it will look like Image-2.png ![Image-2](https://user-images.githubusercontent.com/44690784/60791324-064be100-a181-11e9-80bc-440acf7d1a23.png) I hope it will resolve your issue

Hi @cdhiman 

I tried your code from bitbucket but it didn't worked for me can you plz respond with other solution
Thanks in advance

**Comment by tsaputo** [comment]
Is this issue fixed?

**Comment by eduardomoora** [comment]
Hello I was facing the same issue I found a way to try to solve this 



`
    <ngx-charts-bar-vertical
      [results]="configChart.results"
      [showDataLabel]="true"
      [customColors]="colorScheme"
      [view]="configChart.view"
      [animations]="configChart.animations"
      [legend]="configChart.legend"
      [barPadding]="this.calculatePadding(configChart.results.length)"
      [legendTitle]=""
      [xAxis]="configChart.xAxis"
      [yAxis]="configChart.yAxisLabel"
      [showYAxisLabel]="configChart.showYAxisLabel"
      [yAxisLabel]="configChart.yAxisLabel"
      [dataLabelFormatting]="configChart.dataLabelFormatter"
    ></ngx-charts-bar-vertical>

  calculatePadding(total: number): number{
    switch(total){
      case 1 :
        return 400;
      case 2 :
        return 300;
      case 3:
        return 100
      case 4:
        return 500;
      default:
        return 10
    }
  }

`

in the method calculatePadding you receive the total of results which means how many bars you have so you can use this switch to give padding with to every one of them and the default is the last I simply say if are more than 4 just give 10 and that fit for any other number the problem mostly is when we have few bars and those scenarios are covered by the switch you can always give the number that you preferred
