### ISSUE TITLE
Bundle Size

### ISSUE THREAD

**Issue by cfremgen** [swimlane/ngx-charts#699]
**I'm submitting a ...**  (check one with "x")
```
[x] feature request
```

**Current behavior**
Big bundle size. Nearly half of the size of the Angular framework.

**Reproduction of the problem**
Run webpack bundle analyzer

**What is the motivation / use case for changing the behavior?**
Reduce bundle size

* **ngx-charts version:** x.x.x
7.0.1

* **Angular version:** 2.x.x
5.2.0

Large bundle size for index file:
![image](https://user-images.githubusercontent.com/31008811/35026829-44f0df4a-fb1b-11e7-8310-1f9e5413cb92.png)

I have to import the entire module to use this library. It would be nice to only import the features I am using.

**Comment by sandangel** [comment]
I think you can do so. Only import common and the chart module you use.

**Comment by cfremgen** [comment]
For example,
  
import { ChartCommonModule } from '@swimlane/ngx-charts/release/common';
import { LineChartModule } from '@swimlane/ngx-charts/release/line-chart';

Now I get 404's on the styles

![image](https://user-images.githubusercontent.com/31008811/35072998-f73252c6-fbb4-11e7-847c-f05a7dd55d0c.png)


Do you know how to import the styles too?

**Comment by sandangel** [comment]
you should inline inline the css file during a build process

**Comment by cfremgen** [comment]
Using angular CLI, when inlining through the build process styles are bundled in to the main application styles. This means "tootltip.component.css" file does not exist at the root directory.

**Comment by pietmichal** [comment]
Any progress on this issue?

**Comment by cfremgen** [comment]
No

**Comment by pietmichal** [comment]
I've checked the contents npm module and of noticed the core issue.

It contains the compiled version *only* and this messes up the app compilation when importing specific modules.

Webpack and AOT make sure that components' `styleUrls` are compiled to `styles` which are referring to valid relative paths in the context of the compiled webpack app.

Everything looks fine when you import the whole `@swimlane/ngx-charts` because the `index.js` has all valid webpack imports/exports inside of it.

*The solution*
Provide "raw" TypeScript based source code in the npm module and let the end user compile it within the app and/or use rollup.js instead of webpack for the library.

**Comment by pietmichal** [comment]
Oh, I've used a different import and it works. 

```
import { ChartCommonModule, LineChartModule } from '@swimlane/ngx-charts';
```

**Comment by dparish** [comment]
Update:

I'm running Angular 6.0.1 with ngx-charts 8.0.0.  

My imports look like this:

```javascript
    ...
    ChartCommonModule,
    AreaChartModule,
    BarChartModule,
    LineChartModule,
    NumberCardModule,
    PieChartModule,
    ....
```

I still get a ngx-charts/release/index.js whose stat size is 1.15MB and parsed size is 450k

I had to look it up parsed is after minification

Considering that my entire prod bundle size is 2.2MB, charts is a pretty high percentage. Anything you guys can do to reduce it would be terrific.  Perhaps tree shakable providers is the answer?

**Comment by ShinDarth** [comment]
I can confirm this issue and it looks quite serious.

Using `ngx-charts 9.0.0` the bundle size is **1.64 MB**, almost the same as Angular which for me is 1.78 MB.

![image](https://user-images.githubusercontent.com/75517/44041543-555f6e6c-9f1e-11e8-9639-290d25c2f499.png)


My `ng -v` output:

> Angular CLI: 6.1.3
> Node: 8.10.0
> OS: linux x64
> Angular: 6.1.2
> ... animations, common, compiler, compiler-cli, core, forms
> ... http, language-service, platform-browser
> ... platform-browser-dynamic, router
> 
> Package                           Version
> -----------------------------------------------------------
> @angular-devkit/architect         0.7.3
> @angular-devkit/build-angular     0.6.8
> @angular-devkit/build-optimizer   0.6.8
> @angular-devkit/core              0.7.3
> @angular-devkit/schematics        0.7.3
> @angular/cli                      6.1.3
> @ngtools/webpack                  6.0.8
> @schematics/angular               0.7.3
> @schematics/update                0.7.3
> rxjs                              6.2.2
> typescript                        2.9.2
> webpack                           4.8.3
>

**Comment by cmstuning** [comment]
I fixed this problem by
1. "d3": "^4.10.2", (previously was 5.0.0)
2. Importing only necessary modules (LineChartModule, BarChartModule)

Resulting bundle chunk decreased from 799 KB to 276 KB

**Comment by vmandy** [comment]
I believe I'm having the same issue.

In my case, I simply want to use the `LineChartComponent`, and would like to tree-shake out everything else from my bundle.

like those above, I've tried the following which did not reduce my bundle size when compared to importing `NgxChartsModule`:
```typescript
import { LineChartModule } from '@swimlane/ngx-charts';
```

I then tried the proposed solution above to explicitely import `ChartCommonModule` & `LineChartModule` from their sub-folders under `@swimlane/ngx-charts/release`.

As above, this resulted in a smaller bundle size, but I now have the same CSS errors mentioned above.

I've also tried referring to issues #623 & #22, which both mention tree-shaking. There is even a mention of PR #1004 which supposedly enables tree-shaking. 

I am looking for a definite answer: _Is tree-shaking of this library possible? And if so, can someone please provide a documented example (or Plunker/Stackblitz) of how to do it correctly_

Thank you in advance for your help

**Comment by cfremgen** [comment]
Closing, fixed in https://github.com/swimlane/ngx-charts/pull/1004


Ex:
import { LineChartModule } from '@swimlane/ngx-charts';


@NgModule({
    declarations: [
    ],
    imports: [
        LineChartModule
    ],
    exports: [
    ]
})
export class SharedModule { }

**Comment by nncl** [comment]
Hello, I'm sorry to comment on a closed issue, but for me at least on my two tests that I've made the bundle size of BarChartModule is still big - 1.4MB and when I remove it decreases to just 127KB.

The current version is 13.0.2, on Angular 8. Is there anything else to do in order to reduce its size?

**Comment by marcoripa96** [comment]
Hello, the same problem is happening to me. I'm including only PieChartModule and my component budle size spikes up. As soon as I remove the import the size goes back to normale.

The current version is 13.0.2, on Angular 9.

**Comment by Kyusung4698** [comment]
@marcoripa96 Can confirm this is still an issue with following version:

`@swimlane/ngx-charts: 14.0.0`
`@angular: 9.1.7`

**Comment by EmreAkkoc** [comment]
@swimlane/ngx-charts: 14.0.0
@angular: 9.1.7

adds a whole 1.95 mb to my bundle. too bad, I really liked the gauge charts.

**Comment by tobiso95** [comment]
I am also having this problem. Importing only the PieChartModule results in an import of the whole package.
```
ngx-charts 18.0.1
angular 11.2.3
```
